INSERT TO bears (name, age, gender, color, temperament, alive) VALUES ('Mr. Chocolate',5,'male','Black', 'Good', True)
INSERT TO bears (name, age, gender, color, temperament, alive) VALUES ('Rowdy',4,'male','Black', 'Good', True)
INSERT TO bears (name, age, gender, color, temperament, alive) VALUES ('Tabitha',9,'male','Black', 'Good', True)
INSERT TO bears (name, age, gender, color, temperament, alive) VALUES ('Sergeant Brown',29,'male','Black', 'Good', True)
INSERT TO bears (name, age, gender, color, temperament, alive) VALUES ('Melissa',12,'male','Black', 'Good', True)
INSERT TO bears (name, age, gender, color, temperament, alive) VALUES ('Grinch',11,'male','Black', 'Good', True)
INSERT TO bears (name, age, gender, color, temperament, alive) VALUES ('Wendy',23,'male','Black', 'Good', True)
INSERT TO bears (name, age, gender, color, temperament, alive) VALUES (NULL,9,'male','Black', 'Bad', FALSE)